version: 2.1
jobs:
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run: |
          poetry self update
          pip install --upgrade tox
      - restore_cache:
          keys:
            - v1-poetry-deps-{{ checksum "poetry.lock" }}
            - v1-poetry-deps-
      - run:
          name: Run tox tests
          command: tox -e py39
      - save_cache:
          key: v1-poetry-deps-{{ checksum "poetry.lock" }}
          paths:
            - .tox
  publish-pypi:
    docker:
      - image: cimg/python:3.9
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ab:1b:10:1f:ec:50:a3:2a:f0:92:3e:f9:69:df:d3:63"
      - checkout
      - run:
          name: Install deps
          command: pip install --upgrade toml
      - run:
          name: Publish package to pypi
          command: poetry publish --build --username __token__ --password $PYPI_API_TOKEN
      - run:
          name: Create git tag
          command: pip install -U toml && git tag v$(python3 .circleci/parse_version.py)
      - run:
          name: Push git tag
          command: git push --tags
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test:
          context: polaris-foundation
      - publish-pypi:
          context: polaris-foundation
          requires:
            - test
          filters:
            branches:
              only:
                - main
